### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'getImageList' (Python 3.7)

### ISSUE THREAD

**Issue by rybshik** [sidphbot/Auto-Research#2]
Kaggle  Jupiter notebook with virtual environment  Python 3.7
(does not work with  Python 3.8, 3.9, 3.10)

$ pip install sacremoses
$ pip  install protobuf==3.20.3 --upgrade

%%writefile test.py
from survey import Surveyor
mysurveyor = Surveyor()
mysurveyor.survey('vision transformers')

Writing test.py

$  python3.7 test.py

 File "/kaggle/working/Auto-Research/src/Surveyor.py", line 1084, in extract_images
    images.extend(page.getImageList())
**AttributeError: 'Page' object has no attribute 'getImageList'**

Related info: https://stackoverflow.com/questions/75321414/python-page-object-has-no-attribute-getimagelist-where-i-try-to-extract-im
https://pymupdf.readthedocs.io/en/latest/znames.html

**Comment by sidphbot** [comment]
Hi thanks for checking this out and posting your issue, I have been quite busy since a few months and am not able to post any fixes for now.

The issue here is that some of the dependencies have breaking changes and I forgot to add the exact versions for which it was working. I will try to fix the issues and bring it to a working state when I find some time in the next few months, but feel free to try out the versions available for every dependency during my last commit to this package. If you fix it already before me, feel free to put a pull request I will be happy to merge it.

**Comment by rybshik** [comment]
Hi,
Thanks for your reply.

How can I disable cuda to run on CPU only (without GPU)?

Thanks,
Alex.

**Comment by rybshik** [comment]
Hi,
Thanks for your reply.

How can I disable cuda to run on CPU only (without GPU)?

Thanks,
Alex.
